### ISSUE TITLE
/bundle_uuid/submission_id/

### ISSUE THREAD

**Issue by malloryfreeberg** [rdgoite/hca-clear-tape#1]
In the examples for running the tool, the commands indicate that a bundle UUID needs to be supplied:

```
python clear_tape.py <bundle_uuid>
python clear_tape.py <bundle_uuid> my_bundle
```

but shouldn't it be a `submission_id` that is supplied? At least, it's the submission ID that works for me.

So the commands should be:

```
python clear_tape.py <submission_id>
python clear_tape.py <submission_id> my_bundle
```

**Comment by rdgoite** [comment]
Sorry, I can't remember how this works to be honest. 😅 Might have been back in the day when I didn't completely understand the difference. I'll take a look and update.

**Comment by rdgoite** [comment]
I've reviewed the README and corrected this.

**Comment by malloryfreeberg** [comment]
ty! 👍
