### ISSUE TITLE
Support for staging env

### ISSUE THREAD

**Issue by malloryfreeberg** [rdgoite/hca-clear-tape#2]
Could you add support for using this tool to interrogate a submission in the staging env, since wranglers are only testing submissions in staging at the moment?

**Comment by rdgoite** [comment]
I've added support for staging env in this script. You can now set `CT_ENV` to `STAGING` to use clear tape with staging env:

    export CT_ENV=STAGING && python clear_tape.py <submission_id>

**Comment by malloryfreeberg** [comment]
ty! 🌮
